## Alejandra

In [145]:
import pandas as pd

In [128]:
df = pd.read_csv(r"./dataSet/kiva_loans.csv")
df

,id,funded_amount,loan_amount,activity,sector,use,country_code,country,region,currency,partner_id,posted_time,disbursed_time,funded_time,term_in_months,lender_count,tags,borrower_genders,repayment_interval,date
0,653051,300.0,300.0,Fruits & Vegetables,Food,"To buy seasonal, fresh fruits to sell.",PK,Pakistan,Lahore,PKR,247.0,2014-01-01 06:12:39+00:00,2013-12-17 08:00:00+00:00,2014-01-02 10:06:32+00:00,12.0,12,NaN,female,irregular,2014-01-01
1,653053,575.0,575.0,Rickshaw,Transportation,to repair and maintain the auto rickshaw used ...,PK,Pakistan,Lahore,PKR,247.0,2014-01-01 06:51:08+00:00,2013-12-17 08:00:00+00:00,2014-01-02 09:17:23+00:00,11.0,14,NaN,"female, female",irregular,2014-01-01
2,653068,150.0,150.0,Transportation,Transportation,To repair their old cycle-van and buy another ...,IN,India,Maynaguri,INR,334.0,2014-01-01 09:58:07+00:00,2013-12-17 08:00:00+00:00,2014-01-01 16:01:36+00:00,43.0,6,"user_favorite, user_favorite",female,bullet,2014-01-01
3,653063,200.0,200.0,Embroidery,Arts,to purchase an embroidery machine and a variet...,PK,Pakistan,Lahore,PKR,247.0,2014-01-01 08:03:11+00:00,2013-12-24 08:00:00+00:00,2014-01-01 13:00:00+00:00,11.0,8,NaN,female,irregular,2014-01-01
4,653084,400.0,400.0,Milk Sales,Food,to purchase one buffalo.,PK,Pakistan,Abdul Hakeem,PKR,245.0,2014-01-01 11:53:19+00:00,2013-12-17 08:00:00+00:00,2014-01-01 19:18:51+00:00,14.0,16,NaN,female,monthly,2014-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671200,1340323,0.0,25.0,Livestock,Agriculture,"[True, u'para compara: cemento, arenya y ladri...",PY,Paraguay,Concepción,USD,58.0,2017-07-25 16:55:34+00:00,2017-07-25 07:00:00+00:00,NaN,13.0,0,NaN,female,monthly,2017-07-25
671201,1340316,25.0,25.0,Livestock,Agriculture,"[True, u'to start a turducken farm.'] - this l...",KE,Kenya,NaN,KES,138.0,2017-07-25 06:14:08+00:00,2017-07-24 07:00:00+00:00,2017-07-26 02:09:43+00:00,13.0,1,NaN,female,monthly,2017-07-25
671202,1340334,0.0,25.0,Games,Entertainment,NaN,KE,Kenya,NaN,KES,138.0,2017-07-26 00:02:07+00:00,2017-07-25 07:00:00+00:00,NaN,13.0,0,NaN,NaN,monthly,2017-07-26
671203,1340338,0.0,25.0,Livestock,Agriculture,"[True, u'to start a turducken farm.'] - this l...",KE,Kenya,NaN,KES,138.0,2017-07-26 06:12:55+00:00,2017-07-25 07:00:00+00:00,NaN,13.0,0,NaN,female,monthly,2017-07-26
671204,1340339,0.0,25.0,Livestock,Agriculture,"[True, u'to start a turducken farm.'] - this l...",KE,Kenya,NaN,KES,138.0,2017-07-26 06:31:46+00:00,2017-07-25 07:00:00+00:00,NaN,13.0,0,NaN,female,monthly,2017-07-26

In [129]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 671205 entries, 0 to 671204
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  671205 non-null  int64
 1   funded_amount       671205 non-null  float64
 2   loan_amount         671205 non-null  float64
 3   activity            671205 non-null  str
 4   sector              671205 non-null  str
 5   use                 666973 non-null  str
 6   country_code        671197 non-null  str
 7   country             671205 non-null  str
 8   region              614405 non-null  str
 9   currency            671205 non-null  str
 10  partner_id          657698 non-null  float64
 11  posted_time         671205 non-null  str
 12  disbursed_time      668809 non-null  str
 13  funded_time         622874 non-null  str
 14  term_in_months      671205 non-null  float64
 15  lender_count        671205 non-null  int64
 16  tags                499789 non-null  str
 17  borrower_genders    666984 non-null  str
 18  repayment_interval  671205 non-null  str
 19  date                671205 non-null  str
dtypes: float64(4), int64(2), str(14)
memory usage: 102.4 MB

In [130]:
df.describe()

,id,funded_amount,loan_amount,partner_id,term_in_months,lender_count
count,6.712050e+05,671205.000000,671205.000000,657698.000000,671205.000000,671205.000000
mean,9.932486e+05,785.995061,842.397107,178.199616,13.739022,20.590922
std,1.966113e+05,1130.398941,1198.660073,94.247581,8.598919,28.459551
min,6.530470e+05,0.000000,25.000000,9.000000,1.000000,0.000000
25%,8.230720e+05,250.000000,275.000000,126.000000,8.000000,7.000000
50%,9.927800e+05,450.000000,500.000000,145.000000,13.000000,13.000000
75%,1.163653e+06,900.000000,1000.000000,204.000000,14.000000,24.000000
max,1.340339e+06,100000.000000,100000.000000,536.000000,158.000000,2986.000000

In [131]:
print(df.shape)

(671205, 20)

In [132]:
display(df.head)

<bound method NDFrame.head of              id  funded_amount  loan_amount             activity  \
0        653051          300.0        300.0  Fruits & Vegetables
1        653053          575.0        575.0             Rickshaw
2        653068          150.0        150.0       Transportation
3        653063          200.0        200.0           Embroidery
4        653084          400.0        400.0           Milk Sales
...         ...            ...          ...                  ...
671200  1340323            0.0         25.0            Livestock
671201  1340316           25.0         25.0            Livestock
671202  1340334            0.0         25.0                Games
671203  1340338            0.0         25.0            Livestock
671204  1340339            0.0         25.0            Livestock

                sector                                                use  \
0                 Food            To buy seasonal, fresh fruits to sell.
1       Transportation  to repair and maintain the auto rickshaw used ...
2       Transportation  To repair their old cycle-van and buy another ...
3                 Arts  to purchase an embroidery machine and a variet...
4                 Food                           to purchase one buffalo.
...                ...                                                ...
671200     Agriculture  [True, u'para compara: cemento, arenya y ladri...
671201     Agriculture  [True, u'to start a turducken farm.'] - this l...
671202   Entertainment                                                NaN
671203     Agriculture  [True, u'to start a turducken farm.'] - this l...
671204     Agriculture  [True, u'to start a turducken farm.'] - this l...

       country_code   country        region currency  partner_id  \
0                PK  Pakistan        Lahore      PKR       247.0
1                PK  Pakistan        Lahore      PKR       247.0
2                IN     India     Maynaguri      INR       334.0
3                PK  Pakistan        Lahore      PKR       247.0
4                PK  Pakistan  Abdul Hakeem      PKR       245.0
...             ...       ...           ...      ...         ...
671200           PY  Paraguay    Concepción      USD        58.0
671201           KE     Kenya           NaN      KES       138.0
671202           KE     Kenya           NaN      KES       138.0
671203           KE     Kenya           NaN      KES       138.0
671204           KE     Kenya           NaN      KES       138.0

                      posted_time             disbursed_time  \
0       2014-01-01 06:12:39+00:00  2013-12-17 08:00:00+00:00
1       2014-01-01 06:51:08+00:00  2013-12-17 08:00:00+00:00
2       2014-01-01 09:58:07+00:00  2013-12-17 08:00:00+00:00
3       2014-01-01 08:03:11+00:00  2013-12-24 08:00:00+00:00
4       2014-01-01 11:53:19+00:00  2013-12-17 08:00:00+00:00
...                           ...                        ...
671200  2017-07-25 16:55:34+00:00  2017-07-25 07:00:00+00:00
671201  2017-07-25 06:14:08+00:00  2017-07-24 07:00:00+00:00
671202  2017-07-26 00:02:07+00:00  2017-07-25 07:00:00+00:00
671203  2017-07-26 06:12:55+00:00  2017-07-25 07:00:00+00:00
671204  2017-07-26 06:31:46+00:00  2017-07-25 07:00:00+00:00

                      funded_time  term_in_months  lender_count  \
0       2014-01-02 10:06:32+00:00            12.0            12
1       2014-01-02 09:17:23+00:00            11.0            14
2       2014-01-01 16:01:36+00:00            43.0             6
3       2014-01-01 13:00:00+00:00            11.0             8
4       2014-01-01 19:18:51+00:00            14.0            16
...                           ...             ...           ...
671200                        NaN            13.0             0
671201  2017-07-26 02:09:43+00:00            13.0             1
671202                        NaN            13.0             0
671203                        NaN            13.0             0
671204                        NaN            13.0             0

                                tags borrower_genders repayment_interval  \
0                                NaN           female          irregular
1                                NaN   female, female          irregular
2       user_favorite, user_favorite           female             bullet
3                                NaN           female          irregular
4                                NaN           female            monthly
...                              ...              ...                ...
671200                           NaN           female            monthly
671201                           NaN           female            monthly
671202                           NaN              NaN            monthly
671203                           NaN           female            monthly
671204                           NaN           female            monthly

              date
0       2014-01-01
1       2014-01-01
2       2014-01-01
3       2014-01-01
4       2014-01-01
...            ...
671200  2017-07-25
671201  2017-07-25
671202  2017-07-26
671203  2017-07-26
671204  2017-07-26

[671205 rows x 20 columns]>

In [133]:
display(df.info)

<bound method DataFrame.info of              id  funded_amount  loan_amount             activity  \
0        653051          300.0        300.0  Fruits & Vegetables
1        653053          575.0        575.0             Rickshaw
2        653068          150.0        150.0       Transportation
3        653063          200.0        200.0           Embroidery
4        653084          400.0        400.0           Milk Sales
...         ...            ...          ...                  ...
671200  1340323            0.0         25.0            Livestock
671201  1340316           25.0         25.0            Livestock
671202  1340334            0.0         25.0                Games
671203  1340338            0.0         25.0            Livestock
671204  1340339            0.0         25.0            Livestock

                sector                                                use  \
0                 Food            To buy seasonal, fresh fruits to sell.
1       Transportation  to repair and maintain the auto rickshaw used ...
2       Transportation  To repair their old cycle-van and buy another ...
3                 Arts  to purchase an embroidery machine and a variet...
4                 Food                           to purchase one buffalo.
...                ...                                                ...
671200     Agriculture  [True, u'para compara: cemento, arenya y ladri...
671201     Agriculture  [True, u'to start a turducken farm.'] - this l...
671202   Entertainment                                                NaN
671203     Agriculture  [True, u'to start a turducken farm.'] - this l...
671204     Agriculture  [True, u'to start a turducken farm.'] - this l...

       country_code   country        region currency  partner_id  \
0                PK  Pakistan        Lahore      PKR       247.0
1                PK  Pakistan        Lahore      PKR       247.0
2                IN     India     Maynaguri      INR       334.0
3                PK  Pakistan        Lahore      PKR       247.0
4                PK  Pakistan  Abdul Hakeem      PKR       245.0
...             ...       ...           ...      ...         ...
671200           PY  Paraguay    Concepción      USD        58.0
671201           KE     Kenya           NaN      KES       138.0
671202           KE     Kenya           NaN      KES       138.0
671203           KE     Kenya           NaN      KES       138.0
671204           KE     Kenya           NaN      KES       138.0

                      posted_time             disbursed_time  \
0       2014-01-01 06:12:39+00:00  2013-12-17 08:00:00+00:00
1       2014-01-01 06:51:08+00:00  2013-12-17 08:00:00+00:00
2       2014-01-01 09:58:07+00:00  2013-12-17 08:00:00+00:00
3       2014-01-01 08:03:11+00:00  2013-12-24 08:00:00+00:00
4       2014-01-01 11:53:19+00:00  2013-12-17 08:00:00+00:00
...                           ...                        ...
671200  2017-07-25 16:55:34+00:00  2017-07-25 07:00:00+00:00
671201  2017-07-25 06:14:08+00:00  2017-07-24 07:00:00+00:00
671202  2017-07-26 00:02:07+00:00  2017-07-25 07:00:00+00:00
671203  2017-07-26 06:12:55+00:00  2017-07-25 07:00:00+00:00
671204  2017-07-26 06:31:46+00:00  2017-07-25 07:00:00+00:00

                      funded_time  term_in_months  lender_count  \
0       2014-01-02 10:06:32+00:00            12.0            12
1       2014-01-02 09:17:23+00:00            11.0            14
2       2014-01-01 16:01:36+00:00            43.0             6
3       2014-01-01 13:00:00+00:00            11.0             8
4       2014-01-01 19:18:51+00:00            14.0            16
...                           ...             ...           ...
671200                        NaN            13.0             0
671201  2017-07-26 02:09:43+00:00            13.0             1
671202                        NaN            13.0             0
671203                        NaN            13.0             0
671204                        NaN            13.0             0

                                tags borrower_genders repayment_interval  \
0                                NaN           female          irregular
1                                NaN   female, female          irregular
2       user_favorite, user_favorite           female             bullet
3                                NaN           female          irregular
4                                NaN           female            monthly
...                              ...              ...                ...
671200                           NaN           female            monthly
671201                           NaN           female            monthly
671202                           NaN              NaN            monthly
671203                           NaN           female            monthly
671204                           NaN           female            monthly

              date
0       2014-01-01
1       2014-01-01
2       2014-01-01
3       2014-01-01
4       2014-01-01
...            ...
671200  2017-07-25
671201  2017-07-25
671202  2017-07-26
671203  2017-07-26
671204  2017-07-26

[671205 rows x 20 columns]>

## LIMPIEZA DE DATOS 

- Pasar de tipo str a datatime las fechas

In [134]:
df_type = df.loc[:,['posted_time', 'disbursed_time', 'funded_time', 'date']]
df_type.info()

<class 'pandas.DataFrame'>
RangeIndex: 671205 entries, 0 to 671204
Data columns (total 4 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   posted_time     671205 non-null  str
 1   disbursed_time  668809 non-null  str
 2   funded_time     622874 non-null  str
 3   date            671205 non-null  str
dtypes: str(4)
memory usage: 20.5 MB

In [135]:
colum_df = ['posted_time', 'disbursed_time', 'funded_time', 'date']
for column in colum_df:
    df[column] = pd.to_datetime(df[column]) #Por cada columna cambia a tipo fecha

df_type = df.loc[:,['posted_time', 'disbursed_time', 'funded_time', 'date']]
df_type.info()

<class 'pandas.DataFrame'>
RangeIndex: 671205 entries, 0 to 671204
Data columns (total 4 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   posted_time     671205 non-null  datetime64[us, UTC]
 1   disbursed_time  668809 non-null  datetime64[us, UTC]
 2   funded_time     622874 non-null  datetime64[us, UTC]
 3   date            671205 non-null  datetime64[us]
dtypes: datetime64[us, UTC](3), datetime64[us](1)
memory usage: 20.5 MB

- Nulos

In [136]:
df.isnull().sum()

id                         0
funded_amount              0
loan_amount                0
activity                   0
sector                     0
use                     4232
country_code               8
country                    0
region                 56800
currency                   0
partner_id             13507
posted_time                0
disbursed_time          2396
funded_time            48331
term_in_months             0
lender_count               0
tags                  171416
borrower_genders        4221
repayment_interval         0
date                       0
dtype: int64

In [137]:
print(df.isnull().mean()*100)

id                     0.000000
funded_amount          0.000000
loan_amount            0.000000
activity               0.000000
sector                 0.000000
use                    0.630508
country_code           0.001192
country                0.000000
region                 8.462392
currency               0.000000
partner_id             2.012351
posted_time            0.000000
disbursed_time         0.356970
funded_time            7.200632
term_in_months         0.000000
lender_count           0.000000
tags                  25.538546
borrower_genders       0.628869
repayment_interval     0.000000
date                   0.000000
dtype: float64

In [138]:
print(df.columns)

Index(['id', 'funded_amount', 'loan_amount', 'activity', 'sector', 'use',
       'country_code', 'country', 'region', 'currency', 'partner_id',
       'posted_time', 'disbursed_time', 'funded_time', 'term_in_months',
       'lender_count', 'tags', 'borrower_genders', 'repayment_interval',
       'date'],
      dtype='str')

In [139]:
df = df.drop(columns=['tags'])
df.info() # eliminacion de columna tag ya que supera el 25%

<class 'pandas.DataFrame'>
RangeIndex: 671205 entries, 0 to 671204
Data columns (total 19 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  671205 non-null  int64
 1   funded_amount       671205 non-null  float64
 2   loan_amount         671205 non-null  float64
 3   activity            671205 non-null  str
 4   sector              671205 non-null  str
 5   use                 666973 non-null  str
 6   country_code        671197 non-null  str
 7   country             671205 non-null  str
 8   region              614405 non-null  str
 9   currency            671205 non-null  str
 10  partner_id          657698 non-null  float64
 11  posted_time         671205 non-null  datetime64[us, UTC]
 12  disbursed_time      668809 non-null  datetime64[us, UTC]
 13  funded_time         622874 non-null  datetime64[us, UTC]
 14  term_in_months      671205 non-null  float64
 15  lender_count        671205 non-null  int64
 16  borrower_genders    666984 non-null  str
 17  repayment_interval  671205 non-null  str
 18  date                671205 non-null  datetime64[us]
dtypes: datetime64[us, UTC](3), datetime64[us](1), float64(4), int64(2), str(9)
memory usage: 97.3 MB

- Sustitución de nulos por "No especificado" en caso de string y por la media numerica de la columna en caso de número

In [140]:
#Seleccionar los nombres de las columnas que son texto
columns_str = df.select_dtypes(str).columns
print(columns_str)
for column in columns_str:
    df[column] = df[column].fillna("No especificado")

# Seleccionamos las que son int o float
columns_num = df.select_dtypes('number').columns

for column in columns_num:
    # Calculamos la mediana de la columna
    mediana = df[column].median()
    # Rellenamos los nulos de esa columna con su mediana
    df[column] = df[column].fillna(mediana)

# Verificamos que ya no quedan nulos
print(df.isnull().sum())

Index(['activity', 'sector', 'use', 'country_code', 'country', 'region',
       'currency', 'borrower_genders', 'repayment_interval'],
      dtype='str')
id                        0
funded_amount             0
loan_amount               0
activity                  0
sector                    0
use                       0
country_code              0
country                   0
region                    0
currency                  0
partner_id                0
posted_time               0
disbursed_time         2396
funded_time           48331
term_in_months            0
lender_count              0
borrower_genders          0
repayment_interval        0
date                      0
dtype: int64

In [141]:
df= df.dropna() #borra las filas que tengan valores faltantes
df.info()

<class 'pandas.DataFrame'>
Index: 622633 entries, 0 to 671201
Data columns (total 19 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  622633 non-null  int64
 1   funded_amount       622633 non-null  float64
 2   loan_amount         622633 non-null  float64
 3   activity            622633 non-null  str
 4   sector              622633 non-null  str
 5   use                 622633 non-null  str
 6   country_code        622633 non-null  str
 7   country             622633 non-null  str
 8   region              622633 non-null  str
 9   currency            622633 non-null  str
 10  partner_id          622633 non-null  float64
 11  posted_time         622633 non-null  datetime64[us, UTC]
 12  disbursed_time      622633 non-null  datetime64[us, UTC]
 13  funded_time         622633 non-null  datetime64[us, UTC]
 14  term_in_months      622633 non-null  float64
 15  lender_count        622633 non-null  int64
 16  borrower_genders    622633 non-null  str
 17  repayment_interval  622633 non-null  str
 18  date                622633 non-null  datetime64[us]
dtypes: datetime64[us, UTC](3), datetime64[us](1), float64(4), int64(2), str(9)
memory usage: 95.0 MB

 - Eliminacion de duplicados

In [142]:
df.duplicated().sum() #cuenta el numero de duplicados

np.int64(0)

- Normalización de textos

In [143]:
for column in df.columns:
    if df[column].dtype == 'str':
        df[column] = df[column].str.strip().str.capitalize() #Eliminamos espacios en blanco y ponemos la primera letra en mayusculas

- Normalización de monedas
 Eliminación de country code debido a redundancia con la columna de country y conversión de currency a dolares para poder eliminar la misma columna de country

In [144]:
df = df.drop(columns=['country_code']) #Eliminación de columna contry_code

In [146]:
import requests

# Obtenemos tasas de cambio
response = requests.get('https://api.exchangerate-api.com/v4/latest/USD')
rates_usd_base = response.json()['rates']

#Creamos un diccionario vacio al cual decimos que recorra el de rates_usd_base para invertir los valores
rates_to_usd = {}
for currency, rate in rates_usd_base.items():
    rates_to_usd[currency] = 1 / rate

df['currency'] = df['currency'].str.upper() #normalizamos a mayusculas para que coincidan con los datos de conversion de la API

def get_rate(currency_code):
    return rates_to_usd.get(currency_code, None) # En caso de no encontrar la moneda devolveremos None


#Creamos dos nuevas columnas para meter estos nuevos datos
df['funded_amount_usd'] = df['funded_amount'] * df['currency'].apply(get_rate)
df['loan_amount_usd'] = df['loan_amount'] * df['currency'].apply(get_rate)

In [147]:
df.info()

<class 'pandas.DataFrame'>
Index: 622633 entries, 0 to 671201
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  622633 non-null  int64
 1   funded_amount       622633 non-null  float64
 2   loan_amount         622633 non-null  float64
 3   activity            622633 non-null  str
 4   sector              622633 non-null  str
 5   use                 622633 non-null  str
 6   country             622633 non-null  str
 7   region              622633 non-null  str
 8   currency            622633 non-null  str
 9   partner_id          622633 non-null  float64
 10  posted_time         622633 non-null  datetime64[us, UTC]
 11  disbursed_time      622633 non-null  datetime64[us, UTC]
 12  funded_time         622633 non-null  datetime64[us, UTC]
 13  term_in_months      622633 non-null  float64
 14  lender_count        622633 non-null  int64
 15  borrower_genders    622633 non-null  str
 16  repayment_interval  622633 non-null  str
 17  date                622633 non-null  datetime64[us]
 18  funded_amount_usd   622631 non-null  float64
 19  loan_amount_usd     622631 non-null  float64
dtypes: datetime64[us, UTC](3), datetime64[us](1), float64(6), int64(2), str(8)
memory usage: 99.8 MB

In [148]:
#Eliminar  funded_amount y loan_amount puesto que ya no son necesarias y podemos calcularas en base a funded_amount_usd y la tasa de conversión
df = df.drop(columns=['funded_amount','loan_amount'])

In [150]:
print(df.columns)

Index(['id', 'activity', 'sector', 'use', 'country', 'region', 'currency',
       'partner_id', 'posted_time', 'disbursed_time', 'funded_time',
       'term_in_months', 'lender_count', 'borrower_genders',
       'repayment_interval', 'date', 'funded_amount_usd', 'loan_amount_usd'],
      dtype='str')